# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Unzip the Provar Ant Files'
      if [! -d ProvarHome];
      then
        curl -O https://download.provartesting.com/2.0.5/Provar_ANT_2.0.5.04.zip
        unzip Provar_ANT_2.0.5.04.zip -d ProvarHome;
      else echo 'ProvarHome is present';

      fi
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'xvfb-run ant -Dprovar.home=$(Provar_Home) -f $(build_file)'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'AzureYAML/ANT/Results/JUunit.xml'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'AzureYAML/ANT/Results'
    ArtifactName: 'ResultsDirectory'
    publishLocation: 'Container'


    




